### ISSUE TITLE
Unknown identifier with static vars

### ISSUE THREAD

**Issue by Hinaichigo** [wixoaGit/OpenDream#706] opened 2022-05-30 15:04 UTC
Compiling /vg/station produces the following error:
`Error at code\modules\client\preferences\subsections\limbs.dm:28:29: Unknown identifier "peg_limb_data"`
at the following location in `limbs.dm`:
```
22 var/static/list/peg_limb_data = list(
23	"internal_name" = "peg",
24 	"mode" = LIMB_MODE_SPECIAL_SNOWFLAKE,
25 )
26 
27 var/static/list/leg_configurable_states = list(
28 	"Peg leg" = peg_limb_data,
29 )
```

**Comment by ike709** [comment] 2022-05-30 17:14
Dupe of https://github.com/wixoaGit/OpenDream/issues/693

**Comment by wixoaGit** [comment] 2022-05-30 17:38
> Dupe of #693 ?

They are static vars, nothing here is required to be constant.

**Comment by Altoids1** [comment] 2022-08-20 20:32
I didn't get a compiler error. I think this is fixed?

**Comment by Hinaichigo** [comment] 2022-08-26 04:34
Yep, it seems like it.

**Closed** 2022-09-26 04:37 UTC
Labels: Compiler
